// <auto-generated />
using System;
using MeterVerification.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeterVerification.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeterVerification.Core.Models.DeviceModification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("Name", "DeviceTypeId")
                        .IsUnique();

                    b.ToTable("DeviceModifications");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MeasurementUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("VerificationInterval")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MeasurementUnits");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.Verification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DeviceModificationId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSuitable")
                        .HasColumnType("boolean");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("date");

                    b.Property<DateTime>("VerificationDate")
                        .HasColumnType("date");

                    b.Property<string>("VersionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNumber");

                    b.HasIndex("DeviceModificationId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("IsSuitable");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ValidUntil");

                    b.HasIndex("VerificationDate");

                    b.ToTable("Verifications");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.DeviceModification", b =>
                {
                    b.HasOne("MeterVerification.Core.Models.DeviceType", "DeviceType")
                        .WithMany("Modifications")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.DeviceType", b =>
                {
                    b.HasOne("MeterVerification.Core.Models.MeasurementUnit", "MeasurementUnit")
                        .WithMany("DeviceTypes")
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MeasurementUnit");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.Verification", b =>
                {
                    b.HasOne("MeterVerification.Core.Models.DeviceModification", "DeviceModification")
                        .WithMany("Verifications")
                        .HasForeignKey("DeviceModificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeterVerification.Core.Models.DeviceType", "DeviceType")
                        .WithMany("Verifications")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeterVerification.Core.Models.Organization", "Organization")
                        .WithMany("Verifications")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceModification");

                    b.Navigation("DeviceType");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.DeviceModification", b =>
                {
                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.DeviceType", b =>
                {
                    b.Navigation("Modifications");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.MeasurementUnit", b =>
                {
                    b.Navigation("DeviceTypes");
                });

            modelBuilder.Entity("MeterVerification.Core.Models.Organization", b =>
                {
                    b.Navigation("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
